sonar.projectKey=AntoineLudwigGalli_alice-crm-etudiants
sonar.organization=antoineludwiggalli # Remplacez par votre clé d'organisation sur SonarCloud si différente

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=alice-crm-etudiants
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=src,templates,public

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude vendor and tests from analysis
sonar.exclusions=vendor/**,var/**,tests/**

# Test files
sonar.tests=tests

# PHP settings
sonar.php.coverage.reportPaths=var/coverage.xml
